package com.example.runningapp.other

import android.graphics.Color

object Constants {

    //DATA BASE NAME
    const val RUNNING_DATABASE_NAME= "running_db"

    //PERMISSIONS CONSTANTS
    const val PERMISSIONS_NEEDED_ERROR="You need o accept location permissions to use this app."
    const val REQUEST_CODE_LOCATION_PERMISSION=0

    //TRACKING SERVICE ACTION NAMES THAT ARE SENT FROM THE ACTIVITY TO THE SERVICE
    const val ACTION_START_OR_RESUME_SERVICE="ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE="ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE="ACTION_STOP_SERVICE"
    const val ACTION_SHOW_TRACKING_FRAGMENT="ACTION_SHOW_TRACKING_FRAGMENT"

    //TRACKING SERVICE'S NOTIFICATION CHANNEL PARAMETRES
    const val NOTIFICATION_CHANNEL_ID= "tracking_channel"
    const val NOTIFICATION_CHANNEL_NAME= "Tracking"
    const val NOTIFICATION_ID=1

    //TRACKING LOCATION INTERVAL RESPONSE
    const val LOCATION_UPDATE_INTERVAL=5000L
    const val FASTEST_LOCATION_INTERVAL=2000L
    const val TIMER_UPDATE_INTERVAL=50L

    //POLYLINE ATTRIBUTES
    const val POLYLINE_COLOR= Color.RED
    const val POLYLINE_WIDTH= 8f
    const val MAP_ZOOM= 15f

    // SHARED PREFERENCE NAME AND KEYS
    const val SHARED_PREFERENCES_NAME="sharedPref"
    const val KEY_TOGGLE_FIRST_TIME="KEY_TOGGLE_FIRST_TIME"
    const val KEY_NAME="KEY_NAME"
    const val KEY_WEIGHT="KEY_WEIGHT"


    //SNACKBAR TEXTS FOR FAILS OR SUCCESS
    const val ENTER_ALL_VALUES=" please enter all the values"
    const val CHANGES_MADE_SUCCESSFULLY="CHANGES_MADE_SUCCESSFULLY"


}